### ISSUE TITLE
Top level doc comment

### ISSUE THREAD

**Issue by fishy** [reddit/baseplate.go#102]
Add a top level `doc.go` and `doc_test.go` (at the root directory) to give users a high level overview of how to use the packages, how to manage their main function, etc.

**Comment by pacejackson** [comment]
Can we also add a "tutorial" like what we have in baseplate.py? 

https://baseplate.readthedocs.io/en/stable/tutorial/index.html

The idea is giving devs something to step through to help them understand the parts that go into creating a basic service and let them peek under the hood a little.
