### ISSUE TITLE
Add more sophisticated Logger

### ISSUE THREAD

**Issue by lbelaus** [reddit/baseplate.go#15]
Implement logging other that standard log package

**Comment by fishy** [comment]
We use [zap](https://godoc.org/go.uber.org/zap) in our code, it has higher performance than the [go-kit logging library](https://godoc.org/github.com/go-kit/kit/log) we used before. We can port our zap integration into baseplate.go

That being said, this is still more for baseplate users to use, usage by baseplate itself still need to be careful.

**Comment by fishy** [comment]
Closed with #21
