### ISSUE TITLE
A piece of dead code

### ISSUE THREAD

**Issue by foreverest** [reddit/baseplate.go#234]
The following code never gets executed, since the `err != nil` case is handled above.

https://github.com/reddit/baseplate.go/blob/b28862699aee56a1b96c4bf94b7032bb81f71dd2/thriftbp/client_pool.go#L362-L367

cc @fishy

**Comment by fishy** [comment]
This is not dead code. This is a deferred function with named return. `err` will be whatever error https://github.com/reddit/baseplate.go/blob/b28862699aee56a1b96c4bf94b7032bb81f71dd2/thriftbp/client_pool.go#L371 returns.

**Comment by foreverest** [comment]
Yeah, I see. Sorry 😐.
