### ISSUE TITLE
Edge request context

### ISSUE THREAD

**Issue by fishy** [reddit/baseplate.go#33]
[spec link](https://pages.github.snooguts.net/reddit/baseplate.spec/component-apis/edge-request-context), [baseplate.py implementation link](https://github.com/reddit/baseplate.py/blob/master/baseplate/lib/edge_context.py)

**Comment by pacejackson** [comment]
I think we can close this?

**Comment by fishy** [comment]
The event fields part are not done yet (depending on experiments package).
