### ISSUE TITLE
Prometheus `${protocol}_success` label has different behavior depending on the protocol

### ISSUE THREAD

**Issue by nanassito** [reddit/baseplate.go#495]
Right now `${protocol}_success` is used as a stringified boolean `true | false`. However for user errors (4xx), the http instrumentation logs them as a success, but the thrift instrumentation logs them as a failure.

At the very minimum we should ensure that both have the same behavior.

Since 4xx never really fits completely in errors nor success, I suggest that we remove the `${protocol}_success` label and instead replace it with a new label `${protocol}_status` which would have one of the following values `success | user error | app error`

Opinion?

**Comment by nanassito** [comment]
cc @fishy @kylelemons

**Comment by fishy** [comment]
wait where did the code log http 4xx as success?

in both [server](https://github.com/reddit/baseplate.go/blob/9ad9f79d34867828c720a48b6c8a01aa283867b7/httpbp/middlewares.go#L458) and [client](https://github.com/reddit/baseplate.go/blob/9ad9f79d34867828c720a48b6c8a01aa283867b7/httpbp/client_middlewares.go#L306) middlewares we use `isRequestSuccessful`, which calls [`isSuccessStatusCode`](https://github.com/reddit/baseplate.go/blob/9ad9f79d34867828c720a48b6c8a01aa283867b7/httpbp/middlewares.go#L489) which does not count 4xx as successes: https://github.com/reddit/baseplate.go/blob/9ad9f79d34867828c720a48b6c8a01aa283867b7/httpbp/middlewares.go#L381

**Comment by nanassito** [comment]
not sure what I did but indeed this isn't a problem
